#FROM golang:1.13
#FROM alpine:3.7
#
#COPY build/bm-inventory /bm-inventory
#RUN chmod +x /bm-inventory
#
#ENTRYPOINT ["/bm-inventory"]

FROM scratch
ADD build/bm-inventory /bm-inventory
CMD ["/bm-inventory"]
